title: Zehao's Projects
description: You can find some toy models here.
cuties_description: Some simple and interesting write-ups here!


show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
mathjax: true
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    preview: false
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

include:
  - cuties 
  