title: Zehao's Toys
description: You can find some toy models here.
cuties_description: Some simple and interesting write-ups here!

show_downloads: false
google_analytics:
mathjax: true
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  math_engine_opts:
    preview: false
plugins:
  - jekyll-seo-tag
sass:
  sass_dir: _sass

include:
  - cuties 